on:
  push:
    paths-ignore:
      - 'releng/**'
      - 'charts/**'
      - 'manifests/**'
      - 'k8s-config/**'
      - 'docs/**'
      - '*.md$'

jobs:
  execute-go-tests:
    runs-on: ubuntu-latest
    name:  let's try and install go
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '^3.9.5'
      - run: python --version
        name: "Check python installed"
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            awscli
            packaging
        name: "Install Python requirements with pip"
      - uses: azure/setup-kubectl@v1
        id: install
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm test
        name: "npm test"
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0' # The Go version to download (if necessary) and use.
      - run: go version
        name: "Check go version"
      - uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 0.4.1
            # "TODO - checkout if missing code"
            # "TODO - skip if not code changes, not release"
            # "TODO - docker registry?"
      - name: "make gotest (TODO - parameter passing for LEGACY & FAST_RECONFIGURE modes)"
        # todo - idle timeout here!  3m
        run: |
          export DEV_KUBE_NO_PVC=yes
          export KAT_REQ_LIMIT=900
          export AMBASSADOR_LEGACY_MODE=false
          export AMBASSADOR_FAST_RECONFIGURE=false
          export TEST_XML_DIR=/tmp/test-logs/xml/
          mkdir -p ${TEST_XML_DIR}
          make gotest
      # teardown
      # "TODO - save logs, amb-save-logs"
      # "TODO - store_test_results"
      #   path: /tmp/test-logs/xml/
      # "TODO - dirty-check"

